---
# tasks file for roles/docker
#
- name: Include OS-specific Docker installation
  include_tasks: "install_{{ ansible_distribution | lower | replace(' ', '_') }}.yml"

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: "{{ docker_service_enabled }}"
  become: yes

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: docker_users | length > 0
  become: yes
  notify: Restart Docker

- name: Verify Docker is running
  command: docker --version
  changed_when: false
  register: docker_version

- name: Print Docker version
  debug:
    msg: "{{ docker_version.stdout }}"
